language: r
sudo: required
warnings_are_errors: true

r_binary_packages:
  - ggplot2
  - plyr
  - xtable
  
r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
