// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// loglog_lnl
double loglog_lnl(arma::vec theta, arma::mat y, arma::mat X);
RcppExport SEXP _spduration_loglog_lnl(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(loglog_lnl(theta, y, X));
    return rcpp_result_gen;
END_RCPP
}
// sploglog_lnl
double sploglog_lnl(arma::vec theta, arma::mat y, arma::mat X, arma::mat Z);
RcppExport SEXP _spduration_sploglog_lnl(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(sploglog_lnl(theta, y, X, Z));
    return rcpp_result_gen;
END_RCPP
}
// spweib_lnl
double spweib_lnl(arma::vec theta, arma::mat y, arma::mat X, arma::mat Z);
RcppExport SEXP _spduration_spweib_lnl(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    rcpp_result_gen = Rcpp::wrap(spweib_lnl(theta, y, X, Z));
    return rcpp_result_gen;
END_RCPP
}
// weib_lnl
double weib_lnl(arma::vec theta, arma::mat y, arma::mat X);
RcppExport SEXP _spduration_weib_lnl(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(weib_lnl(theta, y, X));
    return rcpp_result_gen;
END_RCPP
}
