# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Regular Log-logistic likelihood
#' 
#' @param theta Current parameter values. 
#' @param y Dependent variables. 
#' @param X Duration equation covariates.
#' 
#' @keywords internal
loglog_lnl <- function(theta, y, X) {
    .Call(`_spduration_loglog_lnl`, theta, y, X)
}

#' Split-population Log-logistic log likelihood
#' 
#' @param theta Current parameter values. 
#' @param y Dependent variables. 
#' @param X Duration equation covariates.
#' @param Z Risk equation covariates.
#' 
#' @keywords internal
sploglog_lnl <- function(theta, y, X, Z) {
    .Call(`_spduration_sploglog_lnl`, theta, y, X, Z)
}

#' Split-population Weibull log likelihood
#' 
#' @param theta Current parameter values. 
#' @param y Dependent variables. 
#' @param X Duration equation covariates.
#' @param Z Risk equation covariates.
#' 
#' @keywords internal
spweib_lnl <- function(theta, y, X, Z) {
    .Call(`_spduration_spweib_lnl`, theta, y, X, Z)
}

#' Regular weibull log likelihood
#' 
#' @param theta Current parameter values. 
#' @param y Dependent variables. 
#' @param X Duration equation covariates.
#' 
#' @keywords internal
weib_lnl <- function(theta, y, X) {
    .Call(`_spduration_weib_lnl`, theta, y, X)
}

