# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglog_lnl <- function(theta, y, X) {
    .Call('spdurationcpp_loglog_lnl', PACKAGE = 'spdurationcpp', theta, y, X)
}

sploglog_lnl <- function(theta, y, X, Z) {
    .Call('spdurationcpp_sploglog_lnl', PACKAGE = 'spdurationcpp', theta, y, X, Z)
}

spweib_lnl <- function(theta, y, X, Z) {
    .Call('spdurationcpp_spweib_lnl', PACKAGE = 'spdurationcpp', theta, y, X, Z)
}

weib_lnl <- function(theta, y, X) {
    .Call('spdurationcpp_weib_lnl', PACKAGE = 'spdurationcpp', theta, y, X)
}

